version: '2'

services:
  php:
    image: php:5.6-cli
    container_name: hashcode
    hostname: hashcode
    restart: unless-stopped
    entrypoint: tail -f /dev/null
    volumes:
      - .:/usr/hashcode/